let eventDataNew = [
  {
    uid: 1,
    name: "Lady Gaga ends deal with Target over anti-gay issues",
    category: 4,
    categories: "race, ethnicity and identity",
    date: new Date(2011, 2, 9),
  },
  {
    uid: 1,
    name: "Horrifying gang rape and murder in New Delhi, India",
    category: 4,
    categories: "crime and violence",
    date: new Date(2012, 11, 16),
  },
  {
    uid: 1,
    name: "The U.S. military removes a ban against women serving in combat positions",
    category: 4,
    categories: "empowerment",
    date: new Date(2013, 1, 24),
  },
  {
    uid: 1,
    name: "On May 8, 2013, Cleveland Kidnapping Suspect Ariel Castro is charged with four counts of kidnapping and three counts of rape.",
    category: 4,
    categories: "crime and violence",
    date: new Date(2013, 4, 8),
  },
  {
    uid: 1,
    name: "A new Pentagon report found a 50% increase in sexual assault reports in 2013",
    category: 4,
    categories: "crime and violence",
    date: new Date(2014, 5, 1),
  },
  {
    uid: 1,
    name: "Caitlyn Jenner comes out in an interview",
    category: 4,
    categories: "race, ethnicity and identity",
    date: new Date(2015, 4, 24),
  },
  {
    uid: 1,
    name: "A survey for the Department of Defense finds that in the past year 52% of active service members who reported sexual assault had experienced retaliation in the form of professional, social, and administrative actions or punishments.",
    category: 4,
    categories: "crime and violence",
    date: new Date(2015, 4, 18),
  },
  {
    uid: 2,
    name: "People v. Turner: Brock Turner is arrested for sexually assaulting an unconscious woman",
    category: 4,
    categories: "crime and violence",
    date: new Date(2015, 1, 18),
  },
  {
    uid: 1,
    name: "#EndRapeCulture in South Africa",
    category: 4,
    categories: "empowerment",
    date: new Date(2016, 4, 0),
  },
  {
    uid: 2,
    name: "Hillary Clinton becomes the first woman to receive a presidential nomination from a major political party",
    category: 4,
    categories: "empowerment",
    date: new Date(2016, 7, 26),
  },
  {
    uid: 3,
    name: "Trump: “Grab ‘em by the pussy”",
    category: 4,
    categories: "crime and violence",
    date: new Date(2016, 10, 8),
  },
  {
    uid: 4,
    name: "People v. Turner: Brock Turner is convicted for three counts of felony sexual assault",
    category: 4,
    categories: "crime and violence",
    date: new Date(2016, 3, 30),
  },
  {
    uid: 5,
    name: "People v. Turner: Brock Turner is released after spending 3 months in jail",
    category: 4,
    categories: "crime and violence",
    date: new Date(2016, 9, 2),
  },
  {
    uid: 1,
    name: "Multiple actors, including Meryl Streep, come forward and say they were groped by Dustin Hoffman on set.",
    category: 4,
    categories: "crime and violence",
    date: new Date(2017, 1, 1),
  },
  {
    uid: 1,
    name: "#MeToo in U.S.A.",
    category: 4,
    categories: "empowerment",
    date: new Date(2017, 10, 15),
  },
  {
    uid: 2,
    name: "Harvey Weinstein Trial",
    category: 4,
    categories: "crime and violence",
    date: new Date(2017, 10, 0),
  },
  {
    uid: 3,
    name: "#ChurchToo in U.S.A.",
    category: 4,
    categories: "empowerment",
    date: new Date(2017, 11, 0),
  },
  {
    uid: 4,
    name: "#MeTooSTEM and removal of Francisco J. Ayala from UC Irvine",
    category: 4,
    categories: "empowerment",
    date: new Date(2017, 11, 0),
  },
  {
    uid: 5,
    name: "Release of Wonder Woman",
    category: 4,
    categories: "empowerment",
    date: new Date(2017, 5, 15),
  },
  {
    uid: 6,
    name: "Larry Nassar U.S. Gymnastics doctor sexual assault scandal",
    category: 4,
    categories: "crime and violence",
    date: new Date(2017, 12, 0),
  },
  {
    uid: 7,
    name: "Jessie Reyez releases “Gatekeeper”",
    category: 4,
    categories: "empowerment",
    date: new Date(2017, 4, 26),
  },
  {
    uid: 8,
    name: "The 2017 Westminster sexual scandals in the U.K. and resignation of Sir Michael Fallon",
    category: 4,
    categories: "crime and violence",
    date: new Date(2017, 11, 0),
  },
  {
    uid: 8,
    name: "Multiple occurrences of muslim women being forced to remove Hijab in the U.S. and U.K.",
    category: 4,
    categories: "crime and violence",
    date: new Date(2017, 0, 0),
  },
  {
    uid: 1,
    name: "Meghan Markle’s wedding to Prince Harry in U.K.",
    category: 4,
    categories: "no theme",
    date: new Date(2018, 5, 19),
  },
  {
    uid: 2,
    name: "ME TOO bill in U.S. Congress",
    category: 4,
    categories: "empowerment",
    date: new Date(2018, 1, 18),
  },
  {
    uid: 3,
    name: "Priyanka Chopra marries Nick Jonas in India",
    category: 4,
    categories: "no theme",
    date: new Date(2018, 12, 1),
  },
  {
    uid: 4,
    name: "People v. Turner: Brock Turner is convicted by jury trial of three counts of felony sexual assault",
    category: 4,
    categories: "crime and violence",
    date: new Date(2018, 1, 0),
  },
  {
    uid: 5,
    name: "Google’s Andy Rubin sexual misconduct scandal",
    category: 4,
    categories: "crime and violence",
    date: new Date(2018, 10, 25),
  },
  {
    uid: 6,
    name: "Global Women’s March",
    category: 4,
    categories: "empowerment",
    date: new Date(2018, 1, 20),
  },
  {
    uid: 7,
    name: "#MeTooMilitary in U.S.A",
    category: 4,
    categories: "empowerment",
    date: new Date(2018, 1, 0),
  },
  {
    uid: 8,
    name: "#MeToo in India",
    category: 4,
    categories: "empowerment",
    date: new Date(2018, 10, 0),
  },
  {
    uid: 9,
    name: "Mass sexual assaults during the 2018 new year's celebrations in Bangalore",
    category: 4,
    categories: "crime and violence",
    date: new Date(2018, 12, 0),
  },
  {
    uid: 10,
    name: "Indian actress Tanushree Dutta accuses Nana Patekar of sexual harassment",
    category: 4,
    categories: "empowerment",
    date: new Date(2018, 9, 27),
  },
  {
    uid: 11,
    name: "Indian minister of state for External Affairs, MJ Akbar is accused of sexual harassment by several female colleagues through the 'Me Too' Movement in India",
    category: 4,
    categories: "crime and violence",
    date: new Date(2018, 10, 0),
  },
  {
    uid: 12,
    name: "Indian music director Anu Malik is suspended from the jury panel of Indian Idol 2018, after facing multiple allegations of sexual harassment",
    category: 4,
    categories: "crime and violence",
    date: new Date(2018, 10, 21),
  },
  {
    uid: 1,
    name: "Greta Thunberg: Climate Action Summit and sail to NYC",
    category: 4,
    categories: "empowerment",
    date: new Date(2019, 8, 28),
  },
  {
    uid: 2,
    name: "Release of “Surviving R. Kelly” documentary",
    category: 4,
    categories: "empowerment",
    date: new Date(2019, 1, 0),
  },
  {
    uid: 3,
    name: "Arrest of R. Kelly for 10 counts of sexual abuse against four women",
    category: 4,
    categories: "crime and violence",
    date: new Date(2019, 2, 0),
  },
  {
    uid: 1,
    name: "#SayHerName: Murder of Breonna Taylor",
    category: 4,
    categories: "crime and violence",
    date: new Date(2020, 3, 0),
  },
  {
    uid: 2,
    name: "International Women’s Cricket T20",
    category: 4,
    categories: "empowerment",
    date: new Date(2020, 2, 0),
  },
  {
    uid: 2,
    name: "Dalit girl gangraped in Hathras, Uttar Pradesh, India",
    category: 4,
    categories: "crime and violence",
    date: new Date(2020, 8, 14),
  },
  {
    uid: 2,
    name: "Healthcare workers all over the world receive media attention for their crucial role in the COVID-19 pandemic.",
    category: 4,
    categories: "empowerment",
    date: new Date(2020, 4, 0),
  },
  {
    uid: 3,
    name: "Rape and murder of Vanessa Guillén in U.S. military",
    category: 4,
    categories: "crime and violence",
    date: new Date(2020, 4, 22),
  },
  {
    uid: 1,
    name: "16 year old Ma'Khia Bryant is fatally shot by police officer Nicholas Reardon in Columbus, Ohio",
    category: 4,
    categories: "crime and violence",
    date: new Date(2021, 4, 20),
  },
  {
    uid: 2,
    name: "Kamala Harris is sworn in as the first woman and first woman of color vice president of the United States",
    category: 4,
    categories: "empowerment",
    date: new Date(2021, 1, 20),
  },
  {
    uid: 3,
    name: "Oprah with Meghan and Harry and “Megxit”",
    category: 4,
    categories: "empowerment",
    date: new Date(2021, 3, 7),
  },
  {
    uid: 3,
    name: "Study finds that Indian women politicians face more trolling than US, UK counterparts",
    category: 4,
    categories: "no theme",
    date: new Date(2021, 0, 24),
  },
  {
    uid: 3,
    name: "40% Indian women fear online trolls as they access Internet: Nielson report",
    category: 4,
    categories: "no theme",
    date: new Date(2019, 11, 17),
  },
  {
    uid: 3,
    name: "Indian central government passes the Citizenship Amendment Act, by providing a pathway to Indian citizenship for persecuted religious minorities from Afghanistan, Bangladesh and Pakistan who are Hindus, Sikhs, Buddhists, Jains, Parsis or Christians, and arrived in India before the end of December 2014",
    category: 4,
    categories: "race, ethnicity and identity",
    date: new Date(2019, 11, 12),
  },
  {
    uid: 3,
    name: "India saw, for the first time, a sustained countrywide movement led by Women against the CAA-NRC bills",
    category: 4,
    categories: "empowerment",
    date: new Date(2020, 0, 13),
  },
  {
    uid: 3,
    name: "defamation case filed by former Union minister M J Akbar's against journalist Priya Ramani who had accused him of sexual harassment",
    category: 4,
    categories: "crime and violence",
    date: new Date(2021, 4, 5),
  },
  {
    uid: 3,
    name: "A majority judgement which declared the prohibition of entry of women aged between 10 and 50 into Sabarimala temple, as unconstitutional and discriminatory",
    category: 4,
    categories: "race, ethnicity and identity",
    date: new Date(2018, 8, 28),
  },
  {
    uid: 3,
    name: "An Indian Supreme Court Bench declared muslim instantaneous divorce, triple Talaq, as unconstitutional",
    category: 4,
    categories: "race, ethnicity and identity",
    date: new Date(2019, 6, 31),
  },
  {
    uid: 3,
    name: "Indian court grants bail to Nupur Talwar, a dentist accused in the twin murder of her daughter and domestic help",
    category: 4,
    categories: "crime and violence",
    date: new Date(2019, 6, 31),
  },
  {
    uid: 3,
    name: "Kanimozhi Karunanidhi, Member of Parliament, accused in 2G scam, refused bail",
    category: 4,
    categories: "no theme",
    date: new Date(2011, 4, 11),
  },
  {
    uid: 3,
    name: "Accused who set fire to the rape survivor from Unnao, Uttar Pradesh, India, out on bail",
    category: 4,
    categories: "crime and violence",
    date: new Date(2019, 11, 5),
  },
  {
    uid: 3,
    name: "Saudi Arabia lifts travel restrictions on its women",
    category: 4,
    categories: "empowerment",
    date: new Date(2019, 7, 2),
  },
  {
    uid: 3,
    name: "Saudi Arabia makes it legal for women to drive",
    category: 4,
    categories: "empowerment",
    date: new Date(2018, 5, 24),
  },
  {
    uid: 3,
    name: "Multiple women enter inner sanctum of temples across the country, after protest",
    category: 4,
    categories: "race, ethnicity and identity",
    date: new Date(2016, 2, 3),
  },
  {
    uid: 3,
    name: "Section 377: Indian Supreme Court legalizes consensual sexual conduct between adults of the same sex",
    category: 4,
    categories: "empowerment",
    date: new Date(2018, 8, 6),
  },
  {
    uid: 3,
    name: "Women’s Cricket World Cup 2017",
    category: 4,
    categories: "empowerment",
    date: new Date(2017, 5, 23),
  },
  {
    uid: 3,
    name: "The Marikana massacre was the killing of 34 miners by the South African Police Service (SAPS). It took place on 16 August 2012, and was the most lethal use of force by South African security forces against civilians since 1976.",
    category: 4,
    categories: "crime and violence",
    date: new Date(2012, 7, 16),
  },
  {
    uid: 3,
    name: "On 11 April 2015, several South Africans attacked foreigners in a xenophobic attack in Durban, South Africa, which extended to some parts of Johannesburg. Several people, both foreign and South African alike, were killed with some of the killings captured on camera.",
    category: 4,
    categories: "crime and violence",
    date: new Date(2015, 3, 11),
  },
  {
    uid: 3,
    name: "Brutal gang rape and subsequent death of South African teenager",
    category: 4,
    categories: "crime and violence",
    date: new Date(2013, 1, 2),
  },
  {
    uid: 3,
    name: "Monica Lewinsky breaks decade-long media silence",
    category: 4,
    categories: "empowerment",
    date: new Date(2014, 4, 6),
  },
];

export { eventDataNew };
